mimir:
  structuredConfig:
    multitenancy_enabled: true
    ingest_storage:
      enabled: true
    ingester:
      push_grpc_method_enabled: true
      ring:
        replication_factor: 1
        zone_awareness_enabled: false
    store_gateway:
      sharding_ring:
        replication_factor: 1
        zone_awareness_enabled: false
    
    blocks_storage:
      backend: azure
      azure:
        account_name: lgtmstorageecommerce1
        account_key: "<key>"
        container_name: mimir-blocks
    ruler_storage:
      backend: azure
      azure:
        account_name: lgtmstorageecommerce1
        account_key: "<key>"
        container_name: mimir-ruler
    alertmanager_storage:
      backend: azure
      azure:
        account_name: lgtmstorageecommerce1
        account_key: "<key>"
        container_name: mimir-alertmanager

minio:
  enabled: false
kafka:
  enabled: true
  persistence:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  zookeeper:
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
rollout_operator:
  enabled: false

chunksCache:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

resultsCache:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    enabled: false
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    enabled: false
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

compactor:
  replicas: 1
  persistentVolume:
    enabled: false
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

distributor:
  replicas: 1
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

querier:
  replicas: 1
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

query_frontend:
  replicas: 1
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

ruler:
  replicas: 1
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

alertmanager:
  replicas: 1
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
